version: '2'
 
services:
   db:                                                              
    container_name: db
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    mem_limit: 512M
    volumes:                                                        
       - db_data:/var/lib/mysql                                     
       - ./mysql/db:/docker-entrypoint-initdb.d
    restart: always                                                 
    ports:                                                          
      - 6603:3306                                                   
    environment:                                                    
       MYSQL_ROOT_PASSWORD: password                                
       MYSQL_DATABASE: test_db
       MYSQL_USER: testu                                             
       MYSQL_PASSWORD: testp                                         
       lower_case_table_names: 1
    networks:                                                       
       public_net:                                                  
         ipv4_address: ${DB_IP}             
   app:
    container_name: app
    build:
      context: .
      dockerfile: ./apps/Dockerfile
    mem_limit: 512M
    restart: on-failure
    ports:
    - "8080:8080"
    depends_on:
    - "db"
    networks:
      public_net:
        ipv4_address: ${APP_IP}
networks:
    public_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${NETWORK_SUBNET}

volumes:
    #Only required as volume doesn't exist on filesystem. Will be created in /var/lib/docker/volumes
    db_data: {}

